### ISSUE TITLE
Compilation errors : Json.Exn.Error not found

### ISSUE THREAD

**Issue by MawsFr** [glennsl/bs-json#24]
Hello everybody,

I'm new to ReasonReact and i have an errors when I try to run
`bsb -make-world`
command

I ran `npm install` before it

I'm on windows

It says that it can't find Js.Exn.Error

> $ npm run build:bsb
> sentaku-io-front@ build:bsb D:\maws\git\sentaku-io-front
> bsb -make-world
> Warning: refmt version missing. Please set it explicitly, since we may change the default in the future.

> ninja: no work to do.
> ninja: no work to do.
> [1/1] ←[34mBuilding←[39m ←[2msrc\Json.cmj←[22m
> FAILED: src/Json.cmj D:/maws/git/sentaku-io-front/node_modules/@glennsl/bs-json/lib/js/src/Json.bs.js
> D:\maws\git\sentaku-io-front\node_modules\bs-platform\lib\bsc.exe -bs-package-name @glennsl/bs-json  -bs-package-output commonjs:lib\js\src -bs-assume-has-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include   -I src  -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I "D:\maws\git\sentaku-io-front\node_modules\bs-platform\lib\ocaml" -bs-no-version-header -bs-super-errors -no-alias-deps -color always -o src\Json.cmj -c  src\Json.mlast
> 
>   We've found a bug for you!
>   D:\maws\git\sentaku-io-front\node_modules\@glennsl/bs-json\src\Json.ml 12:5-16
> 
>   10 Ôöé let parseOrRaise s =
>   11 Ôöé   try Js.Json.parseExn s with
>   12 Ôöé   | Js.Exn.Error e ->
>   13 Ôöé     let message =
>   14 Ôöé       match Js.Exn.message e with
> 
>   Unbound constructor Js.Exn.Error
> 
> ninja: build stopped: subcommand failed.
> Failure: D:\maws\git\sentaku-io-front\node_modules\bs-platform\lib\ninja.exe
>  Location: D:\maws\git\sentaku-io-front\node_modules\@glennsl/bs-json\lib\bs
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! sentaku-io-front@ build:bsb: `bsb -make-world`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the sentaku-io-front@ build:bsb script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\maws\AppData\Roaming\npm-cache\_logs\2018-03-04T18_18_47_590Z-debug.log
> 

Here is a screenshots of my vscode
It shows package.json, bsconfig.js, and the Json.ml file that can't compile

![Image of vscode](https://i.imgur.com/bj3GkHx.png)

Thank you in advance 😄

**Comment by glennsl** [comment]
Hi. This isn't an issue with `bs-json` itself, so I'll close it, but here's a few thoughts that might help:
- `Js.Exn.Error` is part of `bs-platform` and has been for a long time. It could be that your global `bs-platform` installation is ancient. Run `bsb -version` to check. It should say `2.2.2`.
- The `bsb` dependency is slightly suspect. The `bsb` executable comes with `bs-platform`, so the dependency shouldn't be there.
- It might be that the Windows instalaltion of `bs-platform` is broken. It wouldn't be the first time, although I think I would have heard about it if it was.
- The Reason discord chat is a great place for getting help with troubleshooting issues like these. You can join it here: https://discord.gg/reasonml
- Otherwise, if it's a bug with `bs-platform` you should open an issue on the BuckleScript repository: https://github.com/BuckleScript/bucklescript

**Comment by MawsFr** [comment]
Hello and thank you for your response, I will check my bsb version 😉
