### ISSUE TITLE
Outdated artifacts in in-source build for Bucklescript 3.

### ISSUE THREAD

**Issue by splodingsocks** [glennsl/bs-json#33]
We've been running into runtime errors saying that the `bool` decoder is undefined using bucklescript 3.0.0 and bs-json 1.3.1, and realized that `src/Json_encode.bs.js` appears to be an old artifact. It contains references to `Js_boolean` near the top, as you can see here:

https://unpkg.com/@glennsl/bs-json@1.3.1/src/Json_encode.bs.js

I don't seem to have problems when I include the package and *don't* use an in-source build. In that case a new artifact gets dropped into the `lib` folder, and that new artifact (built using BS 3.0) doesn't use the `Json_encode` module, but just writes the `bool` decoder inline as the identity function.

**Comment by glennsl** [comment]
Hmm, the artifacts aren't meant to be included in the package, but even if they are they should be overwritten by `bsb -make-world`, so seems like this is really an issue with `bsb`. And even if it doesn't, it shouldn't cause runtime errors, since `js_boolean` should still be included, just deprecated. So maybe it's an issue with `bs-platform` too.

I've just added a fix that excludes the js artifacts and published 1.3.2, which should fix it for bs-json at least. Let me know if you still have issues.

**Comment by splodingsocks** [comment]
great, thank you, @glennsl !
