### ISSUE TITLE
Consider having the compiled JS in the package?

### ISSUE THREAD

**Issue by snird** [glennsl/bs-json#34]
A weird case, but worth the shot:
If one builds his code locally, and deploys this build, then `bs-json` won't work, as it is not installed with the compiled JS files, but they are generated only when building with it.
That complicates a deployment, as now the deployment will require `bucklescript` installed in the environment to build everything.

I couldn't find an easy way to deliver the compiled "world" as is into a deployed environment.
Maybe I'm missing something, or maybe missing a current best practice in this community, but I think this use case is fairly wide, just to `npm install` in the deployed environment, and have everything else precompiled.

**Comment by glennsl** [comment]
The JS files wwere removed in 1.3.2 because of a bug in bsb that causes it to not recompile the code if they're present (see #33). But it's also not a good idea to depend on shipped js files, as they will depend on the specific version of `bs-platform` used to compile them, which will be more volatile than the source itself (and was also part of the problem in #33). You also have to install the entire `bs-platform` monstrosity anyway to get the runtime, std lib and such, so you'll have bucklescript installed and ready to be used anyway.

Until the above issues are resovled, I'd recommend bundling the js files before deployment. I'll close this for now, since this isn't something that can be reliably fixed here yet, but please revisit when bucklescript has a good story for it.
