### ISSUE TITLE
Upgrade path for Deprecated Boolean Codec

### ISSUE THREAD

**Issue by dvisztempacct** [glennsl/bs-json#36]
What's the upgrade path for this? For encode I suppose `Obj.magic` will do the trick (although it would be less idiomatic and intuitive IMHO) but for decode, what do we do?

Also, what was e277c2be086f5c90ab21a71d20f5e7cfe88a457b about? Was that to accommodate people who haven't updated `bs-platform` like Issue #31 ? Will there be a new release soon for people have upgraded?

I'm trying pretty hard to get rid of all the annoying compiler warnings :)

**Comment by glennsl** [comment]
You can just use the `bool` encoder/decoder instead, can't you? The serialization format for that is, was and will continue to be js booleans.

The commit you link to was made to maintain backwards compatibility for those that haven't updated, and to not break semantic versioning. And because of how `bsb` works, that means compiler warnings for everyone until a new major version is pushed. I wanted to get some bigger changes into a new major release too, but might consider doing one just to get rid of the warnings. It would be much better if the warning issue was fixed in the `bsb` side though.

Closing this as answered, but let me know if you still have questions.

**Comment by dvisztempacct** [comment]
Any plans for the next major version number?

**Comment by glennsl** [comment]
Big plans. Primarily a more expressive way to decode objects, which also would enable a Result-based API, which I'm considering doing at the same time. Not sure whether it would be less painful to make it one big change, or to do it piecemeal.

Here's what decoding an object probably will look like:
```reason
Json.Decode.(
  obj (fun ~field -> {
    start     = field.required "start" point;
    end_      = field.required "end" point;
    thickness = field.optional "thickness" int
  })
)
```

**Comment by dvisztempacct** [comment]
Mmm... good to know!

Thanks :)
