### ISSUE TITLE
Include `parseAsResult` (or something)

### ISSUE THREAD

**Issue by jaredramirez** [glennsl/bs-json#41]
I was wondering if you would consider adding a function to parse but return [`Belt.Result.t`](https://bucklescript.github.io/bucklescript/api/Belt.Result.html).

The `parse` method already included that returns `Option` is nice because it allows for a more graceful failure, it looses the error message about why the JSON was invalid. The `Result` type doesn't have this limitation since you can specify an failure type. Additionally, it allows for better compile-time bug catching compared to `parseOrRaise`.

Implementation would be relative simple, something like this in `src/Json.ml`:
```
module R = Belt.result;

let parseAsResult s =
  try R.Ok (Js.Json.parseExn s) with
  | Js.Exn.Error e ->
    let message =
      match Js.Exn.message e with
      | Some m  -> m
      | None    -> "Unknown error"
in (R.Error message)
```
(The syntax might be off, I'm not as familiar with ocaml syntax)

Currently the `Result` type (and the entire `Belt` std lib) is in beta, so I wouldn't think this should happen until the API is stable.

**Comment by glennsl** [comment]
Hey. I agree with everything you've said, and the plan is actually to move the entire API to `result`. I even have a branch that already has this implemented. But as you correctly point out, `result` isn't stable yet, and it'd be better to wait until it is. Stability should be just around the corner though, unless Bob has decided to just stop working on it without telling anyone. Which wouldn't really surprise me, but either way we'll just have to wait.

I'll close this since it'll come with the rest and is already on my TODO-list. Thanks for the feedback! Always appreciated :)

**Comment by tcoopman** [comment]
I guess with `Belt.Result` that `result` is stable now?
Is this back on the radar?

**Comment by glennsl** [comment]
Belt unfortunately turned out to be a pile of shit that I'd prefer to avoid. BUT bs-platform v6.0 will be based on OCaml 4.06.1 which includes a standardized `result` type. And it's _just around the corner :tm:_ (This time it really is though, [it just entered pre-release](https://github.com/BuckleScript/bucklescript.github.io/commit/e8345384b763f78ac089b1ece7abe4897e4c31fd?short_path=21da614#diff-21da614013cec0ef0d96b6f87bd0c30f))
