### ISSUE TITLE
Example code spit out a warning

### ISSUE THREAD

**Issue by aaron-michaux** [glennsl/bs-json#48]
For clarity, the example code on the `README.md` page contains:

```
type point = {
  x: float,
  y: float
};

module Decode = {
  let point = json =>
    Json.Decode.{
      x: json |> field("x", float),
      y: json |> field("y", float)
    };
};
```

When trying to compile this, I get:

```
  Warning number 44
  /path/to/Test.re 9:5-12:5
  
   7 │ module Decode = {
   8 │   let point = json =>
   9 │     Json.Decode.{
  10 │       x: json |> field("x", float),
  11 │       y: json |> field("y", float)
  12 │     };
  13 │ };
  14 │ 
  
  this open statement shadows the value identifier float (which is later used)
```

I get this behavior whenever attempting to parse a `float` field.

**Comment by glennsl** [comment]
This is because the `Pervasives` module, which is opened automatically everywhere, annoyingly defines a `float` function so that name is basically reserved. You can get around the warning by qualifying it with the module name, thereby making it unambiguous. Just replace `float` with `Json.Decode.float`.

Still, not a great idea to have an example which emits warnings though, so I think it would be a good idea to replace the `float`s in the example (and [in the examples folder](https://github.com/glennsl/bs-json/blob/master/examples/complex.ml)) with `int`s. Would you like to do a PR for that? Otherwise I'll keep this issue open until I get around to doing it myself. Thanks for the heads up!
