### ISSUE TITLE
How to decode array?

### ISSUE THREAD

**Issue by vonwao** [glennsl/bs-json#49]
It looks like all the examples are JSON objects.   I want to decode an array of objects and create a map out of it, but it's not clear how to accomplish this.  

Also, confused why some examples have .ml extension.   I think they are using an old syntax of Reason?

**Comment by vonwao** [comment]
I will answer my own question.  I was looking for an example, so I didn't notice the documentation.  

Here's my example of parsing a JSON array:

```
module Decode = {
  let doubleArr = json =>
    Json.Decode.( json |> array(int) |> Array.map(_, num => num*2))
};

let data = {| [1, 2, 3] |};

let res = data |> Json.parseOrRaise
                |> Decode.doubleArr;


Js.log(res);
```

**Comment by glennsl** [comment]
Yeah, it's pretty much just `array(whatever)`, so the example is in the documentation of the `array` decoder.

The `.ml` files use OCaml syntax, which can be used as well since this library isn't Reason-specific. Reason is really just an alternative syntax for OCaml after all, so you can switch between the two even within the same project.

**Comment by vasco3** [comment]
I have a similar question, I need to decode an array of objects. But I don't understand the examples in ocaml.

**Comment by vasco3** [comment]
found the solution [here](https://stackoverflow.com/questions/49920131/decoding-a-json-array-of-objects/49921856#49921856)
