### ISSUE TITLE
How to encode option to undefined?

### ISSUE THREAD

**Issue by baransu** [glennsl/bs-json#50]
How to encode `option` into `undefined` which will be removed from JSON by `JSON.stringify`?

`graphql_ppx` generates decoders and encoders for GraphQL queries and in GraphQL if the input argument is optional and not present in the payload to the server it shouldn't be present in the JSON. Currently, we encode it as `null` which breaks some requests because there is no way to encode is as `undefined` or nonexistent.

Original issues: 
- https://github.com/mhallin/graphql_ppx/issues/59
- https://github.com/apollographql/reason-apollo/issues/144

**Comment by glennsl** [comment]
`undefined` is unfortunately not a valid json value. In order to create a json object you have to use `object_`, which takes a list of key-value tuples. To omit a field you'd just omit the corresponding tuple, which seems a lot cleaner to me anyway since the existence of a field on an object is a property of the object, not of the value.

I assume you have some limitation `graphql_ppx` that makes it difficult to do so, but I'm not familiar enough with it to understand what it is and to offer any more specific suggestions unfortunately. And while I'm not going to make the library unsound in order to fix this, please let me know if there's anything else I can do :)

**Comment by baransu** [comment]
Thank you for your answer! It explained it for me very well. I totaly forgot about omitting key/value tuple.
