### ISSUE TITLE
Thoughts on a "runParse" function?

### ISSUE THREAD

**Issue by twopoint718** [glennsl/bs-json#51]
It would seem like a common use case to both parse and convert in a single step:

```reason
let runParse: (Js.Json.t => 'a, string) => option('a) = (decoder, json) =>
  Json.parse(json) |. Belt.Option.map(decoder);
```

with the idea that then there's never any raw `Js.Json.t` value floating around. We've gone directly from a JSON blob, to (optionally) our domain value. In the docs there's the example:

```reason
let line = data |> Json.parseOrRaise
                |> Decode.line;
```

which could have the equivalent:

```reason
let line = Json.runParseOrRaise(Decode.line, data);
```

Just a thought. Thanks!

**Comment by glennsl** [comment]
Hey. I'm not sure I see the benefit of this. Being able to handle raw `Js.Json.t` values can be very useful when dealing with JS interop, and I much prefer small composable functions to lots of specialized functions because the former is more flexible and take better advantage of existing knowledge such as being able to use `Option.map`  with `option`s, or any other `Option` functions.

**Comment by twopoint718** [comment]
@glennsl sure I guess I can see that. And it's not like it's a huge burden to write the function that I have above ;). One other thing that I noticed is that `parse` returns `Js.Json.t option`. It could be nice to have an `either` type as a return value. I see `result` mentioned a few times in the docs, is that what this is/was?

**Comment by glennsl** [comment]
Yes, decoders used to return `result`s, but partly because there's no standard `result` type (yet, but it's coming) and partly for other ergonomic reasons I removed them in favour of raising exceptions, or in the case of `parse`, using an `option`.

Mentions of `result` in the docs should be considered bugs, but I'll most likely rewrite it to use `result`s in the foreseeable future anyway, after BuckleScript has been upgraded to 4.06 with the standard `result` type and after making a few other changes to ease the ergonomic pains.
