### ISSUE TITLE
Decoding a function

### ISSUE THREAD

**Issue by idkjs** [glennsl/bs-json#85]
Is there a way to decode a function as in this example:

```json

{"myfunction": helloWorld()}

```

You might run a check and see that the value is a function like 
```ocaml 
let isFunction = a => Js_types.test(Js_types.Function, a);
```
 then need to decode it.

I'm not sure this would be the right way to do it.

Thanks.

**Comment by glennsl** [comment]
Functions aren't valid JSON (hence why it's marked in red above), so this would really be outside the scope of this library. But more generally the problem is that a function isn't just a function, you also need to know the types of its arguments and return type and there's really no way to test for that.

**Comment by idkjs** [comment]
@glennsl thank you, sir. I am not understanding the js code then. Will go back to it.
